### ISSUE TITLE
Rails 6 compatibility 

### ISSUE THREAD

**Issue by fameoflight** [ilyakatz/data-migrate#119]
I know rails 6 is still in beta so just opening this issue to track the rails 6 compatibility. Here is the error in rails 6

```
Traceback (most recent call last):
	49: from bin/rails:10:in `<main>'
	48: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `require'
	47: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:263:in `load_dependency'
	46: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
	45: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	44: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	43: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	42: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	41: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	40: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/railties-6.0.0.beta3/lib/rails/commands.rb:18:in `<main>'
	39: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/railties-6.0.0.beta3/lib/rails/command.rb:46:in `invoke'
	38: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/railties-6.0.0.beta3/lib/rails/command/base.rb:65:in `perform'
	37: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	36: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	35: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	34: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:136:in `perform'
	33: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:136:in `tap'
	32: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:139:in `block in perform'
	31: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `require'
	30: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:263:in `load_dependency'
	29: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
	28: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	27: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	26: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	24: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	23: from /Users/hemantv/goodly/config/application.rb:8:in `<main>'
	22: from /Users/hemantv/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:114:in `require'
	21: from /Users/hemantv/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	20: from /Users/hemantv/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	19: from /Users/hemantv/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	18: from /Users/hemantv/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
	17: from /Users/hemantv/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	16: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	15: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	14: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	13: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	12: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	11: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/data_migrate-5.3.2/lib/data_migrate.rb:27:in `<main>'
	10: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `require'
	 9: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:263:in `load_dependency'
	 8: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
	 7: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 6: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 5: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 4: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 3: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 2: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/data_migrate-5.3.2/lib/data_migrate/migration.rb:1:in `<main>'
	 1: from /Users/hemantv/.rvm/gems/ruby-2.6.0/gems/data_migrate-5.3.2/lib/data_migrate/migration.rb:2:in `<module:DataMigrate>'
/Users/hemantv/.rvm/gems/ruby-2.6.0/gems/activerecord-6.0.0.beta3/lib/active_record/migration.rb:529:in `inherited': Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: (StandardError)

  class DataMigrate::Migration < ActiveRecord::Migration[4.2]
```

**Comment by ilyakatz** [comment]
Thanks for opening this. I hope this will just be a matter of updating the version of rails used. Let's keep it open and I'll try to get to this soon

**Comment by ilyakatz** [comment]
Started on this in #120

**Comment by ilyakatz** [comment]
Hi @fameoflight, looks like all tests are passing on rails6 branch, would you be able to give it a shot to see if it works in your rails 6 app?

Thanks

**Comment by jaredmoody** [comment]
`rails6` branch seems to be working for me on `6.0.0.rc1` 👍🏼

**Comment by ilyakatz** [comment]
great, thanks for confirming. i merged the PR and released beta version into ruby gems. if i don't get any reported issues, will drop the beta designation
