### ISSUE TITLE
Migration to Rails 6.0.0.rc1 Throws Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for

### ISSUE THREAD

**Issue by estebanbouza** [ilyakatz/data-migrate#125]
Rails version used: 6.0.0.rc1
data_migrate version: 5.3.2

The following error is shown when booting:

```
	42: from bin/rails:3:in `<main>'
	41: from bin/rails:3:in `load'
	40: from /Users/xxxxx/projects/projectname/bin/spring:15:in `<top (required)>'
	39: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	38: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	37: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	36: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	35: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	34: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	33: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	32: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	31: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	30: from /Users/xxxxx/projects/projectname/bin/rails:9:in `<top (required)>'
	29: from /Users/xxxxx/projects/projectname/bin/rails:9:in `require'
	28: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	27: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:46:in `invoke'
	26: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command/base.rb:65:in `perform'
	25: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	24: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	22: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:138:in `perform'
	21: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:138:in `tap'
	20: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	19: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	18: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
	17: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
	16: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	15: from /Users/xxxxx/projects/projectname/config/application.rb:6:in `<top (required)>'
	14: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler.rb:114:in `require'
	13: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	12: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	11: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	10: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
	 9: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	 8: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
	 7: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/data_migrate-5.3.2/lib/data_migrate.rb:27:in `<top (required)>'
	 6: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	 5: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
	 4: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
	 3: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	 2: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/data_migrate-5.3.2/lib/data_migrate/migration.rb:1:in `<top (required)>'
	 1: from /Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/data_migrate-5.3.2/lib/data_migrate/migration.rb:2:in `<module:DataMigrate>'
/Users/xxxxx/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/migration.rb:536:in `inherited': Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: (StandardError)

  class DataMigrate::Migration < ActiveRecord::Migration[4.2]
```

I have seen similar tickets in this github repo opened in the past but they didn't give me enough information to solve the issue. Any indications?

**Comment by ilyakatz** [comment]
what does your data_migration file look like?

**Comment by ilyakatz** [comment]
please ignore. version 4 of data migrate does not support Rails 6. Please upgrade data_migrate gem

**Comment by estebanbouza** [comment]
I'm not sure I understand what you mean? I'm using version `5.3.2` of `data_migrate`. The error `class DataMigrate::Migration < ActiveRecord::Migration[4.2]` is hardcoded from Rails directly: https://github.com/rails/rails/blob/f813119aeca22a87adc68a4843edd7fa8a28272a/activerecord/lib/active_record/migration.rb#L539

As for my `data_migration` file, I'm not sure if you refer to a sample migration one. In that case I have a bunch of them, and they look like this

```
class AddDefaultFreeTrialDays < ActiveRecord::Migration[5.2]
  def up
    Settings.create!(
      key: :some_key,
      value: 7,
    )
  end
  [...]
end

```

**Comment by ilyakatz** [comment]
data_migrate 5.3.2 does not support Rails 6. Can you please try 6.0.1.beta?

**Comment by estebanbouza** [comment]
It's a bit confusing partly because I can't find tags in this repository.

When you say try 6.0.1.beta you refer to `data_migrate` or `rails` version? The current latest rails version seems to be `6.0.0.rc1` as of now, but I can't find the version tag `6.0.1.beta` in this repo.

**Comment by ilyakatz** [comment]
Are you looking for a git tag? (there was someone else asking about tags in the repo so I'd like to understand what people are asking)

But, I meant a version in rubygems https://rubygems.org/gems/data_migrate/versions/6.0.1.beta

So do this in your Gemfile

```
gem 'data_migrate', '6.0.1.beta'
```

**Comment by estebanbouza** [comment]
Ah I understand. That seems to work.

In regards to tags, typically gems (or in non-ruby world libraries) have a tag in the repository with the version number whenever there is a release. I navigate to this page always when I want to know more: https://github.com/ilyakatz/data-migrate/tags

This way it's easy to navigate the documentation and code of a specific version or see what versions have been released meanwhile. I was a very surprised to see that I was running v5.x after a `bundle update` while the last tag shows 3.x in this repo, and at the same time I was getting from you that I should use v6.x.

Anyway thanks for the quick responses and great support! :)

**Comment by ilyakatz** [comment]
Ah I see what you mean. Thanks for the explanation. Let me know if you have any more issues with the beta version

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
