### ISSUE TITLE
ActiveRecord::Migrator signature changed on 6.0.0.rc2 release

### ISSUE THREAD

**Issue by berkos** [ilyakatz/data-migrate#127]
👋 
There seems to be an incompatibility when there is an upgrade to Rails `6.0.0.rc2` and data-migrate gem when running the command `db:migrate:with_data`.

[`ActiveRecord::Migrator#initialize`](https://github.com/rails/rails/blob/v6.0.0.rc2/activerecord/lib/active_record/migration.rb#L1189) has an extra argument which is: `schema_migration`.
PR adding this https://github.com/rails/rails/pull/36439/files#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6R1187.

stack trace:
```
** Invoke db:migrate:with_data (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:migrate:with_data
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 3..4)
.../2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.rc2/lib/active_record/migration.rb:1189:in `initialize'
.../2.6.3/lib/ruby/gems/2.6.0/gems/data_migrate-6.0.1.beta/lib/data_migrate/schema_migration_five.rb:8:in `new'
.../2.6.3/lib/ruby/gems/2.6.0/gems/data_migrate-6.0.1.beta/lib/data_migrate/schema_migration_five.rb:8:in `pending_schema_migrations'
.../2.6.3/lib/ruby/gems/2.6.0/gems/data_migrate-6.0.1.beta/lib/data_migrate/database_tasks.rb:49:in `pending_schema_migrations'
.../2.6.3/lib/ruby/gems/2.6.0/gems/data_migrate-6.0.1.beta/tasks/databases.rake:348:in `pending_migrations'
.../2.6.3/lib/ruby/gems/2.6.0/gems/data_migrate-6.0.1.beta/tasks/databases.rake:14:in `block (3 levels) in <main>'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
.../2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
.../2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
.../2.6.3/bin/rake:23:in `load'
.../2.6.3/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate:with_data

```

Steps to reproduce:

1. Upgrade to Rails `6.0.0.rc2`
1. Run `bundle exec rails db:migrate:with_data`
Thanks 🙂

**Comment by berkos** [comment]
Closing this issue as it has been resolved by https://github.com/ilyakatz/data-migrate/pull/128.

Thanks @y-yagi
