### ISSUE TITLE
TypeError when booting Rails after upgrading

### ISSUE THREAD

**Issue by kaspernj** [ilyakatz/data-migrate#170]
Possibly after #169

```
TypeError: Invalid type for configuration. Expected Symbol, String, or Hash. Got #<ActiveRecord::DatabaseConfigurations::UrlConfig:0x0000563ddf8efaa8 @env_name="development", @spec_name="primary", @config={"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>"username", "password"=>"secret", "host"=>"postgres", "port"=>5432, "database"=>"database"}, @url="postgresql://username:secret@postgres:5432">
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/rails-8956e4ca4a5b/activerecord/lib/active_record/connection_adapters/connection_specification.rb:224:in `resolve_connection'
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/rails-8956e4ca4a5b/activerecord/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/rails-8956e4ca4a5b/activerecord/lib/active_record/connection_handling.rb:170:in `resolve_config_for_connection'
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/rails-8956e4ca4a5b/activerecord/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/data-migrate-392b6025e4f4/lib/data_migrate/data_migrator_five.rb:13:in `assure_data_schema_table'
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/data-migrate-392b6025e4f4/tasks/databases.rake:409:in `assure_data_schema_table'
/home/dev/.rvm/gems/ruby-2.7.2/bundler/gems/data-migrate-392b6025e4f4/tasks/databases.rake:7:in `block (3 levels) in <main>'
...
```

**Comment by ilyakatz** [comment]
Thanks for reporting. I yanked the version from rubygems and have a PR to revert the commit
