### ISSUE TITLE
Rails 6.1.6: "undefined method `schema_dump_path`

### ISSUE THREAD

**Issue by nzifnab** [ilyakatz/data-migrate#295]
I'm getting an error on rails 6.1 when I try to use `rake db:schema:load:with_data` with the error:

rake aborted!
NoMethodError: undefined method `schema_dump_path' for primary:Module
Did you mean?  schema_up_to_date?
/home/zifnab/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/data_migrate-9.2.0/lib/data_migrate/database_tasks.rb:84:in `schema_sha1'
/home/zifnab/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/activerecord-6.1.6/lib/active_record/tasks/database_tasks.rb:334:in `load_schema'

It looks like that method isn't added to the rails module until rails 7, and causes this crash in rails 6. Any chance we can get a patch to fix this?

**Comment by MrKirat** [comment]
HI @nzifnab !
I'm facing the same issue. Have you found any solution for this?
Thank you
