### ISSUE TITLE
ArgumentError: db_configs_with_versions in Rails 7.1.0 - 7.1.3.4

### ISSUE THREAD

**Issue by nickstanish** [ilyakatz/data-migrate#335]
Upgrading data_migrate to v11 is failing for me in CI
```
bin/rails aborted!
2024-09-04 15:23:07.620148 D [3748:59400] ActiveRecord::Base --    (3.8ms)  CREATE TABLE "data_migrations" ("version" character varying NOT NULL PRIMARY KEY)
ArgumentError: wrong number of arguments (given 0, expected 1) (ArgumentError)

Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
```

I believe this is a regression due to https://github.com/ilyakatz/data-migrate/pull/326 changing the parameters to `db_configs_with_versions` in 7.1+ when it should be 7.1.4+

https://github.com/rails/rails/blob/v7.1.4/activerecord/lib/active_record/tasks/database_tasks.rb#L266

https://github.com/rails/rails/blob/v7.1.3.4/activerecord/lib/active_record/tasks/database_tasks.rb#L258

https://github.com/rails/rails/blob/v7.1.3/activerecord/lib/active_record/tasks/database_tasks.rb#L258

**Comment by talal7860** [comment]
+1

**Comment by artyrcheek** [comment]
+1

**Comment by ilyakatz** [comment]
thanks for reporting this. are you able to make PR for this by anychance? or, @bruno-costanzo do you know how to fix this?

**Comment by bruno-costanzo** [comment]
Yes, I think so. I will give it a try tomorrow. Should be fixed just creating an specific helper for Rails 7.1.4 and avoid using the 7.1. Apparently, the change detected in Rails was after 7.1.4.

**Comment by maurobender** [comment]
Hi! I'm seeing this issue in rails 7.1.3.4 and is preventing me from using the gem. Do we know when it'll be fixed or is there any workaround while we're waiting for the next release with the fix?

Thanks!

**Comment by hiemanshu** [comment]
+1 We're seeing the same issue as maurobender, and we're on Rails 7.1.3.4.

**Comment by maurobender** [comment]
Still seeing this issue in version `11.1.0`:

```sh
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1) (ArgumentError)
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/tasks/database_tasks.rb:258:in `db_configs_with_versions'
/usr/local/bundle/gems/data_migrate-11.1.0/lib/data_migrate/database_tasks.rb:183:in `migrate_with_data'
/usr/local/bundle/gems/data_migrate-11.1.0/tasks/databases.rake:9:in `block (3 levels) in <main>'
/usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
```

Is there any plans to merge the fix created by @vprigent and release a new version? Is there any workaround on this to use the gem?
