### ISSUE TITLE
data:schema:load not working with Rails 6.0

### ISSUE THREAD

**Issue by andser** [ilyakatz/data-migrate#338]
Using last possible version for Rails 6.0: 9.1.1. data:schema:load raises error:
```
[DEBUG][18/Sep/2024:13:38:23.542 +0300 #1152][{:pid=>1152}]    (1.7ms)  SELECT version FROM "data_migrations" level=0 _time_local=2024-09-18 10:38:23.542 version=1.1 _pid=1152
[DEBUG][18/Sep/2024:13:38:23.565 +0300 #1152][{:pid=>1152}]   ActiveRecord::InternalMetadata Load (1.4ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]] level=0 _time_local=2024-09-18 10:38:23.565 version=1.1 _pid=1152
rails aborted!
ArgumentError: unknown keyword: :name
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/database_configurations.rb:38:in `configs_for'
/usr/local/bundle/gems/data_migrate-9.1.1/lib/data_migrate/database_tasks.rb:84:in `schema_sha1'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:336:in `load_schema'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
/usr/local/bundle/gems/data_migrate-9.1.1/tasks/databases.rake:285:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => data:schema:load
(See full trace by running task with --trace)
```
Looks like `def configs_for(env_name: nil, spec_name: nil, include_replicas: false)` should receive `spec_name` instead of `name`.
Also `ActiveRecord::Tasks::DatabaseTasks.schema_dump_path` doesn't exist in Rails 6.0.

**Comment by jgmontoya** [comment]
Which version of data_migrate are you using?

**Comment by vprigent** [comment]
@andser is using data_migrate-9.1.1, which is the last available version for Rails 6.0
I'm looking at landing a PR today that would fix the 9.1.x series.
Would you mind reviewing it when ready @jgmontoya ?

**Comment by jgmontoya** [comment]
> @andser is using data_migrate-9.1.1, which is the last available version for Rails 6.0 I'm looking at landing a PR today that would fix the 9.1.x series. Would you mind reviewing it when ready @jgmontoya ?
> 
> While Rails 6.0 is EOL, there's still people out there relying on it, and a fix specific for 9.1.x shouldn't be too much compatibility issues.

Oh I totally missed the data_migrate version, now I see it's the first thing on the issue description 😅 
Yeah I can take a look at your PR no problem! Just tag me on it or something :D

**Comment by vprigent** [comment]
@jgmontoya if you'd like to give #342 a quick review, I'll be able to push it and publish a new 9.1.2 gem version.

**Comment by vprigent** [comment]
Hi @andser , would you like to give 9.1.2 a go please?

**Comment by andser** [comment]
> Hi @andser , would you like to give 9.1.2 a go please?

Checked. Now another error raised:
```ruby
[DEBUG][24/Sep/2024:10:22:40.149 +0300 #1472][{:pid=>1472}]    (0.8ms)  SELECT version FROM "data_migrations" level=0 _time_local=2024-09-24 07:22:40.149 version=1.1 _pid=1472
[DEBUG][24/Sep/2024:10:22:40.169 +0300 #1472][{:pid=>1472}]   ActiveRecord::InternalMetadata Load (0.9ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]] level=0 _time_local=2024-09-24 07:22:40.169 version=1.1 _pid=1472
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/fx/backend/db/schema.rb
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:502:in `read'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:502:in `schema_sha1'
/usr/local/bundle/gems/data_migrate-9.1.2/lib/data_migrate/database_tasks.rb:89:in `schema_sha1'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:336:in `load_schema'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
/usr/local/bundle/gems/data_migrate-9.1.2/tasks/databases.rake:285:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => data:schema:load
(See full trace by running task with --trace)
``` 
data_mgirate gem creates db/data_schema.rb

**Comment by jgmontoya** [comment]
@andser I think that method is supposed to return the original `db/schema.rb` do  you not have a `schema.rb` file on your app?

**Comment by andser** [comment]
> @andser I think that method is supposed to return the original `db/schema.rb` do you not have a `schema.rb` file on your app?

No. We have db/schema_cache.yml. This file generated by db:schema:cache:dump rake task.
```
config.active_record.use_schema_cache_dump enables users to get schema cache information from db/schema_cache.yml (generated by rails db:schema:cache:dump), instead of having to send a query to the database to get this information. Defaults to true.
``` 
https://guides.rubyonrails.org/v6.0/configuring.html#configuring-active-record

**Comment by jgmontoya** [comment]
> > @andser I think that method is supposed to return the original `db/schema.rb` do you not have a `schema.rb` file on your app?
> 
> No. We have db/schema_cache.yml. This file generated by db:schema:cache:dump rake task.
> 
> > config.active_record.use_schema_cache_dump enables users to get schema cache information from db/schema_cache.yml (generated by rails db:schema:cache:dump), instead of having to send a query to the database to get this information. Defaults to true.
> 
> https://guides.rubyonrails.org/v6.0/configuring.html#configuring-active-record

Do you have a `structure.sql`?
Is this a setting on your project: `config.active_record.schema_format = :sql` ?

**Comment by andser** [comment]
@jgmontoya Yep. Set as `config.active_record.schema_format = :sql`

**Comment by jgmontoya** [comment]
I think you should be using `rake db:structure:load:with_data ` instead of `rake db:schema:load:with_data `

**Comment by andser** [comment]
@jgmontoya db:structure:load:with_data :
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/fx/backend/db/schema.rb
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:502:in `read'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:502:in `schema_sha1'
/usr/local/bundle/gems/data_migrate-9.1.2/lib/data_migrate/database_tasks.rb:89:in `schema_sha1'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:336:in `load_schema'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.5.1/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
/usr/local/bundle/gems/data_migrate-9.1.2/tasks/databases.rake:186:in `block (4 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:structure:load:with_data
(See full trace by running task with --trace)
```

**Comment by jgmontoya** [comment]
ok I see the problem, @vprigent fyi this needs a different approach, namely to implement https://github.com/ilyakatz/data-migrate/pull/281 on a way that's compatible with rails 6.0

**Comment by vprigent** [comment]
@andser out of curiosity, which was the last working version for you?

I suspect it was broken before 9.1.1 (which is what I retrofitted yesterday) but I could be wrong.

**Comment by andser** [comment]
@vprigent I started using this gem from 9.1.1. Downgraded to couple of versions. 9.0.0 working ok, without errors:
```
[DEBUG][25/Sep/2024:09:40:41.338 +0300 #14174][{:pid=>14174}]    (1.0ms)  SELECT version FROM "data_migrations" level=0 _time_local=2024-09-25 06:40:41.338 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.341 +0300 #14174][{:pid=>14174}]   SQL (2.5ms)  INSERT INTO "data_migrations" (version) VALUES ('20240917082159') level=0 _time_local=2024-09-25 06:40:41.341 version=1.1 _pid=14174
INSERT INTO "data_migrations" (version) VALUES ('20240917082159')
[INFO][25/Sep/2024:09:40:41.341 +0300 #14174][{:pid=>14174} data:schema:load] INSERT INTO "data_migrations" (version) VALUES ('20240917082159') level=1 _time_local=2024-09-25 06:40:41.341 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.344 +0300 #14174][{:pid=>14174}]   SQL (0.9ms)  INSERT INTO "data_migrations" (version) VALUES ('20240830103107') level=0 _time_local=2024-09-25 06:40:41.344 version=1.1 _pid=14174
INSERT INTO "data_migrations" (version) VALUES ('20240830103107')
[INFO][25/Sep/2024:09:40:41.345 +0300 #14174][{:pid=>14174} data:schema:load] INSERT INTO "data_migrations" (version) VALUES ('20240830103107') level=1 _time_local=2024-09-25 06:40:41.345 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.364 +0300 #14174][{:pid=>14174}]   ActiveRecord::InternalMetadata Load (1.0ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]] level=0 _time_local=2024-09-25 06:40:41.364 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.372 +0300 #14174][{:pid=>14174}]   ActiveRecord::InternalMetadata Load (0.5ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "schema_sha1"], ["LIMIT", 1]] level=0 _time_local=2024-09-25 06:40:41.372 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.374 +0300 #14174][{:pid=>14174}]    (0.3ms)  BEGIN level=0 _time_local=2024-09-25 06:40:41.374 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.374 +0300 #14174][{:pid=>14174}]   ActiveRecord::InternalMetadata Update (0.5ms)  UPDATE "ar_internal_metadata" SET "value" = $1, "updated_at" = $2 WHERE "ar_internal_metadata"."key" = $3  [["value", "b7a30fd43c2dc6c1eae84108ed0b04c84670536e"], ["updated_at", "2024-09-25 06:40:41.372937"], ["key", "schema_sha1"]] level=0 _time_local=2024-09-25 06:40:41.374 version=1.1 _pid=14174
[DEBUG][25/Sep/2024:09:40:41.376 +0300 #14174][{:pid=>14174}]    (0.9ms)  COMMIT level=0 _time_local=2024-09-25 06:40:41.376 version=1.1 _pid=14174
```

**Comment by jgmontoya** [comment]
Hmm so it was likely this change I'd guess #272

**Comment by vprigent** [comment]
@andser I've pushed a new version 9.1.3 which this time should work exactly like 9.0 used to work for rails 6.x

**Comment by andser** [comment]
Many thanks! Works as expected.
