### ISSUE TITLE
Deprecation warning when using Rails 7.2

### ISSUE THREAD

**Issue by martingregoire** [ilyakatz/data-migrate#340]
### Issue

We are currently upgrading our application to Rails 7.2, including an upgrade of the data_migrate gem from 9.4.2 to 11.0.0.

After these upgrades we see the following deprecation warning when starting the Rails server:

```
DEPRECATION WARNING: ActiveRecord::ConnectionAdapters::ConnectionPool#connection is deprecated
and will be removed in Rails 8.0. Use #lease_connection instead.
 (called from <main> at bin/rails:4)

.../gems/data_migrate-11.0.0/lib/data_migrate/database_tasks.rb:27:in `block in with_temporary_connection'
.../gems/data_migrate-11.0.0/lib/data_migrate/database_tasks.rb:43:in `with_temporary_pool'
.../gems/data_migrate-11.0.0/lib/data_migrate/database_tasks.rb:26:in `with_temporary_connection'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:473:in `block in load_schema_current'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:595:in `block (2 levels) in each_current_configuration'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:592:in `each'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:592:in `block in each_current_configuration'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:603:in `each'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:603:in `each_current_environment'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:591:in `each_current_configuration'
.../gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:472:in `load_schema_current'
.../gems/data_migrate-11.0.0/tasks/databases.rake:248:in `block (3 levels) in <main>'
```

The warning is caused by this method call:

https://github.com/ilyakatz/data-migrate/blob/2d29c02d943f4ad01851a8e1cf6e3533aa0dcdde/lib/data_migrate/database_tasks.rb#L25-L29

### Reference

I found the following similar code in the Rails repository. They are using `pool.with_connection(&block)`:

https://github.com/rails/rails/blob/97169912f197eee6e76fafb091113bddf624aa67/activerecord/lib/active_record/tasks/database_tasks.rb#L520

Please see the following commit, where this change was introduced and the deprecation was added:
https://github.com/rails/rails/commit/7263da542b66084dae93af8bc3bd502c8710154b

Maybe the deprecation warning can be fixed in data_migrate in a similar way?

**Comment by martingregoire** [comment]
This was resolved in #341.
