### ISSUE TITLE
Gem Load Error: Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by safetypins** [ilyakatz/data-migrate#80]
Just tried to include the data_migrate gem in my application, but when I try to generate a data migration, I get this error:

```
Traceback (most recent call last):
	18: from bin/rails:4:in '<main>'
	17: from bin/rails:4:in 'require'
	16: from /Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in '<top (required)>'
	15: from /Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:44:in 'invoke'
	14: from /Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in 'perform'
	13: from /Users/matthew/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in 'dispatch'
	12: from /Users/matthew/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in 'invoke_command'
	11: from /Users/matthew/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in 'run'
	10: from /Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/generate/generate_command.rb:19:in 'perform'
	 9: from /Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/actions.rb:15:in 'require_application_and_environment!'
	 8: from /Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/actions.rb:15:in 'require'
	 7: from /Users/matthew/work/bible_reading/config/application.rb:7:in '<top (required)>'
	 6: from /Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in 'require'
	 5: from /Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in 'require'
	 4: from /Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in 'each'
	 3: from /Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in 'block in require'
	 2: from /Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in 'each'
	 1: from /Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in 'block (2 levels) in require'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in 'rescue in block (2 levels) in require': There was an error while trying to load the gem 'data_migrate'. (Bundler::GemRequireError)
Gem Load Error is: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class DataMigrate::Migration < ActiveRecord::Migration[4.2]
Backtrace for gem load error is:
/Users/matthew/.gem/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:525:in 'inherited'
/Users/matthew/.gem/ruby/2.5.0/gems/data_migrate-3.0.1/lib/data_migrate/migration.rb:2:in '<module:DataMigrate>'
/Users/matthew/.gem/ruby/2.5.0/gems/data_migrate-3.0.1/lib/data_migrate/migration.rb:1:in '<top (required)>'
/Users/matthew/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in 'require'
/Users/matthew/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in 'block in require'
/Users/matthew/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in 'load_dependency'
/Users/matthew/.gem/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in 'require'
/Users/matthew/.gem/ruby/2.5.0/gems/data_migrate-3.0.1/lib/data_migrate.rb:3:in '<top (required)>'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in 'require'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in 'block (2 levels) in require'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in 'each'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in 'block in require'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in 'each'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in 'require'
/Users/matthew/.gem/ruby/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in 'require'
/Users/matthew/work/bible_reading/config/application.rb:7:in '<top (required)>'
/Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/actions.rb:15:in 'require'
/Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/actions.rb:15:in 'require_application_and_environment!'
/Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/generate/generate_command.rb:19:in 'perform'
/Users/matthew/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in 'run'
/Users/matthew/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in 'invoke_command'
/Users/matthew/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in 'dispatch'
/Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in 'perform'
/Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:44:in 'invoke'
/Users/matthew/.gem/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in '<top (required)>'
bin/rails:4:in 'require'
bin/rails:4:in '<main>'
Bundler Error Backtrace:
```

**Comment by ilyakatz** [comment]
that's interesting. i see you're using version 3.0.1. do you get the same error with the latest version of data-migrate?

**Comment by safetypins** [comment]
When I remove the version restriction, I don't get a different version with bundle install.
```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'rails',              '~> 5.1.4'
gem 'puma',               '~> 3.7'
gem 'sass-rails',         '~> 5.0'
gem 'uglifier',           '>= 1.3.0'
gem 'coffee-rails',       '~> 4.2'
gem 'turbolinks',         '~> 5'
gem 'bcrypt',             '~> 3.1.7'
gem 'bootstrap-sass',     '3.3.7'
gem 'jbuilder',           '~> 2.5'
gem 'font-awesome-sass',  '~> 4.7.0'
gem 'faker',              '1.7.3'
gem 'will_paginate',      '3.1.6'
gem 'pg',                 '0.18.4'
gem 'data_migrate'
gem 'autoprefixer-rails'
gem 'bitters'
gem 'bourbon'
gem 'dotenv-rails'
gem 'jquery-rails'
gem 'json'
gem 'nprogress-rails'
gem 'neat'
gem 'refills'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

group :development, :test do
  gem 'sqlite3',  '1.3.13'
  gem 'byebug',   '9.0.6', platform: :mri
  gem 'capybara', '~> 2.13'
end

group :test do
  gem 'guard',                    '2.13.0'
  gem 'guard-minitest',           '2.4.4'
  gem 'minitest-reporters',       '1.1.14'
  gem 'rails-controller-testing', '1.0.2'
end

group :development do
  gem 'listen',                '3.1.5'
  gem 'spring',                '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
  gem 'web-console',           '3.5.1'
end

group :production do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by ilyakatz** [comment]
make sure to do `bundle update data_migrate`

**Comment by safetypins** [comment]
I manually updated the version to 3.3.1, and I don't see that error. Thanks!
